connect to bigsql XXconnectXX;

CREATE HADOOP TABLE XXtableXX (ID VARCHAR(100), num INT, fl DOUBLE, st VARCHAR(100), tm TIMESTAMP) partitioned by (part int) XXstorageformatXX;

ALTER TABLE XXtableXX ADD PARTITION (part=0);
ALTER TABLE XXtableXX ADD PARTITION (part=1);
ALTER TABLE XXtableXX ADD PARTITION (part=2);
ALTER TABLE XXtableXX ADD PARTITION (part=3);
ALTER TABLE XXtableXX ADD PARTITION (part=4);
ALTER TABLE XXtableXX ADD PARTITION (part=5);
ALTER TABLE XXtableXX ADD PARTITION (part=6);
ALTER TABLE XXtableXX ADD PARTITION (part=7);
ALTER TABLE XXtableXX ADD PARTITION (part=8);
ALTER TABLE XXtableXX ADD PARTITION (part=9);

terminate;
